#!/usr/bin/env perl

use strict;
use autodie;

use Text::CSV;
use FindBin;

my $csv = Text::CSV->new();
open my $fh, $ARGV[0];
while (my $row = $csv->getline($fh)) {
  next unless $row->[1] eq 'Cue';
  my $number = $row->[3];
  my $name = $row->[6];
  print "$number: $name\n";
  `osascript $FindBin::Bin/q_import.scpt "$name" $number`;
}
close $fh;
